title: nthd3gr33's blog
author: nthd3gr33
email: tweet @ me
description: > # this means to ignore newlines until "baseurl:"
  Personal and professional blog for nthd3gr33

# social links
twitter_username: nthd3gr33 # DO NOT include the @ character, or else the build will fail!
github_username:  nthd3gr33 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
